/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IJuiceStakerDelegateActions,
  IJuiceStakerDelegateActionsInterface,
} from "../IJuiceStakerDelegateActions";

const _abi = [
  {
    inputs: [],
    name: "InvalidNonce",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidSender",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidSignature",
    type: "error",
  },
  {
    inputs: [],
    name: "PermissionExpired",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        components: [
          {
            components: [
              {
                internalType: "address",
                name: "sender",
                type: "address",
              },
              {
                internalType: "uint256",
                name: "deadline",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "nonce",
                type: "uint256",
              },
            ],
            internalType: "struct Permission",
            name: "data",
            type: "tuple",
          },
          {
            internalType: "bytes",
            name: "signature",
            type: "bytes",
          },
        ],
        internalType: "struct SignedPermission",
        name: "permission",
        type: "tuple",
      },
    ],
    name: "delegateDeposit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "address",
            name: "token",
            type: "address",
          },
          {
            internalType: "uint128",
            name: "amount",
            type: "uint128",
          },
          {
            internalType: "bool",
            name: "sentiment",
            type: "bool",
          },
        ],
        internalType: "struct StakingParam[]",
        name: "stakes",
        type: "tuple[]",
      },
      {
        components: [
          {
            components: [
              {
                internalType: "address",
                name: "sender",
                type: "address",
              },
              {
                internalType: "uint256",
                name: "deadline",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "nonce",
                type: "uint256",
              },
            ],
            internalType: "struct Permission",
            name: "data",
            type: "tuple",
          },
          {
            internalType: "bytes",
            name: "signature",
            type: "bytes",
          },
        ],
        internalType: "struct SignedPermission",
        name: "permission",
        type: "tuple",
      },
    ],
    name: "delegateModifyStakes",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        components: [
          {
            components: [
              {
                internalType: "address",
                name: "sender",
                type: "address",
              },
              {
                internalType: "uint256",
                name: "deadline",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "nonce",
                type: "uint256",
              },
            ],
            internalType: "struct Permission",
            name: "data",
            type: "tuple",
          },
          {
            internalType: "bytes",
            name: "signature",
            type: "bytes",
          },
        ],
        internalType: "struct SignedPermission",
        name: "permission",
        type: "tuple",
      },
    ],
    name: "delegateWithdraw",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IJuiceStakerDelegateActions__factory {
  static readonly abi = _abi;
  static createInterface(): IJuiceStakerDelegateActionsInterface {
    return new utils.Interface(_abi) as IJuiceStakerDelegateActionsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IJuiceStakerDelegateActions {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IJuiceStakerDelegateActions;
  }
}
