/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IJuiceOwnerActions,
  IJuiceOwnerActionsInterface,
} from "../IJuiceOwnerActions";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "targetLength",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "amountLength",
        type: "uint256",
      },
    ],
    name: "MintTargetMismatch",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint8",
        name: "expected",
        type: "uint8",
      },
      {
        internalType: "uint8",
        name: "actual",
        type: "uint8",
      },
    ],
    name: "OracleDecimalMismatch",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokensLength",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "oraclesLength",
        type: "uint256",
      },
    ],
    name: "TokenOracleMismatch",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "contract IJuiceSignalAggregator",
        name: "aggregator",
        type: "address",
      },
    ],
    name: "authorizeSignalAggregator",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bool",
        name: "pauseStaking",
        type: "bool",
      },
    ],
    name: "emergencyPause",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address[]",
        name: "recipients",
        type: "address[]",
      },
      {
        internalType: "uint256[]",
        name: "amounts",
        type: "uint256[]",
      },
    ],
    name: "mintJuice",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address[]",
        name: "tokens",
        type: "address[]",
      },
      {
        internalType: "contract IPriceOracle[]",
        name: "oracles",
        type: "address[]",
      },
    ],
    name: "updatePriceOracles",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IJuiceOwnerActions__factory {
  static readonly abi = _abi;
  static createInterface(): IJuiceOwnerActionsInterface {
    return new utils.Interface(_abi) as IJuiceOwnerActionsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IJuiceOwnerActions {
    return new Contract(address, _abi, signerOrProvider) as IJuiceOwnerActions;
  }
}
