/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IJuiceSignalAggregator,
  IJuiceSignalAggregatorInterface,
} from "../IJuiceSignalAggregator";

const _abi = [
  {
    inputs: [
      {
        components: [
          {
            components: [
              {
                internalType: "address",
                name: "token",
                type: "address",
              },
              {
                internalType: "uint96",
                name: "weight",
                type: "uint96",
              },
            ],
            internalType: "struct LongTokenSignal[]",
            name: "longTokens",
            type: "tuple[]",
          },
        ],
        internalType: "struct AggregateTokenSignal",
        name: "tokenSignal",
        type: "tuple",
      },
    ],
    name: "signalUpdated",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IJuiceSignalAggregator__factory {
  static readonly abi = _abi;
  static createInterface(): IJuiceSignalAggregatorInterface {
    return new utils.Interface(_abi) as IJuiceSignalAggregatorInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IJuiceSignalAggregator {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IJuiceSignalAggregator;
  }
}
