"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.IUniswapV3MintCallback__factory = void 0;
var ethers_1 = require("ethers");
var _abi = [
    {
        inputs: [
            {
                internalType: "uint256",
                name: "amount0Owed",
                type: "uint256",
            },
            {
                internalType: "uint256",
                name: "amount1Owed",
                type: "uint256",
            },
            {
                internalType: "bytes",
                name: "data",
                type: "bytes",
            },
        ],
        name: "uniswapV3MintCallback",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
];
var IUniswapV3MintCallback__factory = /** @class */ (function () {
    function IUniswapV3MintCallback__factory() {
    }
    IUniswapV3MintCallback__factory.createInterface = function () {
        return new ethers_1.utils.Interface(_abi);
    };
    IUniswapV3MintCallback__factory.connect = function (address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    };
    IUniswapV3MintCallback__factory.abi = _abi;
    return IUniswapV3MintCallback__factory;
}());
exports.IUniswapV3MintCallback__factory = IUniswapV3MintCallback__factory;
