import { Token as UniswapToken } from '@uniswap/sdk-core';
import { BigNumber, Contract, providers, Signer } from 'ethers';
import { VanillaVersion } from './types/general';
import { Token, UniSwapToken } from './types/trade';
export declare const weth: Token;
export declare const usdc: Token;
export declare const vnl: Token;
export declare function getAllTokens(version?: VanillaVersion): Token[];
export declare function getBalance(address: string, provider: providers.Provider): Promise<BigNumber>;
export declare function isAddress(value: string): string | false;
export declare function getContract(address: string, ABI: any, signerOrProvider?: providers.Provider | Signer | undefined): Contract;
export declare function padUniswapTokenToToken(input: UniSwapToken): Token;
export declare function convertVanillaTokenToUniswapToken(input: Token): UniswapToken;
