"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.IPeripheryImmutableState__factory = void 0;
var ethers_1 = require("ethers");
var _abi = [
    {
        inputs: [],
        name: "WETH9",
        outputs: [
            {
                internalType: "address",
                name: "",
                type: "address",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "factory",
        outputs: [
            {
                internalType: "address",
                name: "",
                type: "address",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
];
var IPeripheryImmutableState__factory = /** @class */ (function () {
    function IPeripheryImmutableState__factory() {
    }
    IPeripheryImmutableState__factory.createInterface = function () {
        return new ethers_1.utils.Interface(_abi);
    };
    IPeripheryImmutableState__factory.connect = function (address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    };
    IPeripheryImmutableState__factory.abi = _abi;
    return IPeripheryImmutableState__factory;
}());
exports.IPeripheryImmutableState__factory = IPeripheryImmutableState__factory;
