"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.IVanillaV1MigrationState__factory = void 0;
var ethers_1 = require("ethers");
var _abi = [
    {
        inputs: [],
        name: "MigrationStateUpdateDisabled",
        type: "error",
    },
    {
        inputs: [],
        name: "UnauthorizedAccess",
        type: "error",
    },
    {
        inputs: [],
        name: "blockNumber",
        outputs: [
            {
                internalType: "uint64",
                name: "",
                type: "uint64",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "conversionDeadline",
        outputs: [
            {
                internalType: "uint64",
                name: "",
                type: "uint64",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "stateRoot",
        outputs: [
            {
                internalType: "bytes32",
                name: "",
                type: "bytes32",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "bytes32",
                name: "newStateRoot",
                type: "bytes32",
            },
            {
                internalType: "uint64",
                name: "blockNum",
                type: "uint64",
            },
        ],
        name: "updateConvertibleState",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "bytes32[]",
                name: "proof",
                type: "bytes32[]",
            },
            {
                internalType: "address",
                name: "tokenOwner",
                type: "address",
            },
            {
                internalType: "uint256",
                name: "amount",
                type: "uint256",
            },
        ],
        name: "verifyEligibility",
        outputs: [
            {
                internalType: "bool",
                name: "",
                type: "bool",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
];
var IVanillaV1MigrationState__factory = /** @class */ (function () {
    function IVanillaV1MigrationState__factory() {
    }
    IVanillaV1MigrationState__factory.createInterface = function () {
        return new ethers_1.utils.Interface(_abi);
    };
    IVanillaV1MigrationState__factory.connect = function (address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    };
    IVanillaV1MigrationState__factory.abi = _abi;
    return IVanillaV1MigrationState__factory;
}());
exports.IVanillaV1MigrationState__factory = IVanillaV1MigrationState__factory;
