"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.IVanillaV1Safelist01__factory = void 0;
var ethers_1 = require("ethers");
var _abi = [
    {
        inputs: [],
        name: "UnauthorizedAccess",
        type: "error",
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: false,
                internalType: "address[]",
                name: "tokens",
                type: "address[]",
            },
        ],
        name: "TokensAdded",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: false,
                internalType: "address[]",
                name: "tokens",
                type: "address[]",
            },
        ],
        name: "TokensRemoved",
        type: "event",
    },
    {
        inputs: [
            {
                internalType: "address",
                name: "token",
                type: "address",
            },
        ],
        name: "isSafelisted",
        outputs: [
            {
                internalType: "bool",
                name: "",
                type: "bool",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "nextVersion",
        outputs: [
            {
                internalType: "address",
                name: "",
                type: "address",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
];
var IVanillaV1Safelist01__factory = /** @class */ (function () {
    function IVanillaV1Safelist01__factory() {
    }
    IVanillaV1Safelist01__factory.createInterface = function () {
        return new ethers_1.utils.Interface(_abi);
    };
    IVanillaV1Safelist01__factory.connect = function (address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    };
    IVanillaV1Safelist01__factory.abi = _abi;
    return IVanillaV1Safelist01__factory;
}());
exports.IVanillaV1Safelist01__factory = IVanillaV1Safelist01__factory;
