"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.IVanillaV1MigrationTarget02__factory = void 0;
var ethers_1 = require("ethers");
var _abi = [
    {
        inputs: [
            {
                internalType: "address",
                name: "owner",
                type: "address",
            },
            {
                internalType: "address",
                name: "token",
                type: "address",
            },
            {
                internalType: "uint256",
                name: "ethSum",
                type: "uint256",
            },
            {
                internalType: "uint256",
                name: "tokenSum",
                type: "uint256",
            },
            {
                internalType: "uint256",
                name: "weightedBlockSum",
                type: "uint256",
            },
            {
                internalType: "uint256",
                name: "latestBlock",
                type: "uint256",
            },
        ],
        name: "migrateState",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
];
var IVanillaV1MigrationTarget02__factory = /** @class */ (function () {
    function IVanillaV1MigrationTarget02__factory() {
    }
    IVanillaV1MigrationTarget02__factory.createInterface = function () {
        return new ethers_1.utils.Interface(_abi);
    };
    IVanillaV1MigrationTarget02__factory.connect = function (address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    };
    IVanillaV1MigrationTarget02__factory.abi = _abi;
    return IVanillaV1MigrationTarget02__factory;
}());
exports.IVanillaV1MigrationTarget02__factory = IVanillaV1MigrationTarget02__factory;
