"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.IVanillaV1Converter__factory = void 0;
var ethers_1 = require("ethers");
var _abi = [
    {
        inputs: [],
        name: "ConversionWindowClosed",
        type: "error",
    },
    {
        inputs: [],
        name: "FreezerBalanceMismatch",
        type: "error",
    },
    {
        inputs: [],
        name: "NoConvertibleVNL",
        type: "error",
    },
    {
        inputs: [],
        name: "UnexpectedTokensAfterConversion",
        type: "error",
    },
    {
        inputs: [],
        name: "VerificationFailed",
        type: "error",
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: false,
                internalType: "address",
                name: "converter",
                type: "address",
            },
            {
                indexed: false,
                internalType: "uint256",
                name: "amount",
                type: "uint256",
            },
        ],
        name: "VNLConverted",
        type: "event",
    },
    {
        inputs: [
            {
                internalType: "bytes32[]",
                name: "proof",
                type: "bytes32[]",
            },
        ],
        name: "checkEligibility",
        outputs: [
            {
                internalType: "bool",
                name: "convertible",
                type: "bool",
            },
            {
                internalType: "bool",
                name: "transferable",
                type: "bool",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "bytes32[]",
                name: "proof",
                type: "bytes32[]",
            },
        ],
        name: "convertVNL",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [],
        name: "migrationState",
        outputs: [
            {
                internalType: "contract IVanillaV1MigrationState",
                name: "",
                type: "address",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
];
var IVanillaV1Converter__factory = /** @class */ (function () {
    function IVanillaV1Converter__factory() {
    }
    IVanillaV1Converter__factory.createInterface = function () {
        return new ethers_1.utils.Interface(_abi);
    };
    IVanillaV1Converter__factory.connect = function (address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    };
    IVanillaV1Converter__factory.abi = _abi;
    return IVanillaV1Converter__factory;
}());
exports.IVanillaV1Converter__factory = IVanillaV1Converter__factory;
