"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var __extends = (this && this.__extends) || (function () {
    var extendStatics = function (d, b) {
        extendStatics = Object.setPrototypeOf ||
            ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
            function (d, b) { for (var p in b) if (Object.prototype.hasOwnProperty.call(b, p)) d[p] = b[p]; };
        return extendStatics(d, b);
    };
    return function (d, b) {
        if (typeof b !== "function" && b !== null)
            throw new TypeError("Class extends value " + String(b) + " is not a constructor or null");
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.MockVanillaV1MigrationTarget02__factory = void 0;
var ethers_1 = require("ethers");
var _abi = [
    {
        anonymous: false,
        inputs: [
            {
                indexed: false,
                internalType: "address",
                name: "owner",
                type: "address",
            },
            {
                indexed: false,
                internalType: "address",
                name: "token",
                type: "address",
            },
            {
                indexed: false,
                internalType: "uint256",
                name: "ethSum",
                type: "uint256",
            },
            {
                indexed: false,
                internalType: "uint256",
                name: "tokenSum",
                type: "uint256",
            },
            {
                indexed: false,
                internalType: "uint256",
                name: "weightedBlockSum",
                type: "uint256",
            },
            {
                indexed: false,
                internalType: "uint256",
                name: "latestBlock",
                type: "uint256",
            },
        ],
        name: "MigrationParams",
        type: "event",
    },
    {
        inputs: [
            {
                internalType: "address",
                name: "owner",
                type: "address",
            },
            {
                internalType: "address",
                name: "token",
                type: "address",
            },
            {
                internalType: "uint256",
                name: "ethSum",
                type: "uint256",
            },
            {
                internalType: "uint256",
                name: "tokenSum",
                type: "uint256",
            },
            {
                internalType: "uint256",
                name: "weightedBlockSum",
                type: "uint256",
            },
            {
                internalType: "uint256",
                name: "latestBlock",
                type: "uint256",
            },
        ],
        name: "migrateState",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
];
var _bytecode = "0x608060405234801561001057600080fd5b50610153806100206000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c80637616f4f314610030575b600080fd5b61004361003e3660046100c9565b610045565b005b604080516001600160a01b03808916825287166020820152908101859052606081018490526080810183905260a081018290527f9210241898c0a0aaf9556f5cc7340586c62f8525a91d2dd4f630dd3b3d133b4b9060c00160405180910390a1505050505050565b80356001600160a01b03811681146100c457600080fd5b919050565b60008060008060008060c087890312156100e1578182fd5b6100ea876100ad565b95506100f8602088016100ad565b95989597505050506040840135936060810135936080820135935060a090910135915056fea2646970667358221220e796314e84b3130b132c85c04c07ebdb6ef35426744a329a4b505e650b8a98f164736f6c63430008040033";
var MockVanillaV1MigrationTarget02__factory = /** @class */ (function (_super) {
    __extends(MockVanillaV1MigrationTarget02__factory, _super);
    function MockVanillaV1MigrationTarget02__factory(signer) {
        return _super.call(this, _abi, _bytecode, signer) || this;
    }
    MockVanillaV1MigrationTarget02__factory.prototype.deploy = function (overrides) {
        return _super.prototype.deploy.call(this, overrides || {});
    };
    MockVanillaV1MigrationTarget02__factory.prototype.getDeployTransaction = function (overrides) {
        return _super.prototype.getDeployTransaction.call(this, overrides || {});
    };
    MockVanillaV1MigrationTarget02__factory.prototype.attach = function (address) {
        return _super.prototype.attach.call(this, address);
    };
    MockVanillaV1MigrationTarget02__factory.prototype.connect = function (signer) {
        return _super.prototype.connect.call(this, signer);
    };
    MockVanillaV1MigrationTarget02__factory.createInterface = function () {
        return new ethers_1.utils.Interface(_abi);
    };
    MockVanillaV1MigrationTarget02__factory.connect = function (address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    };
    MockVanillaV1MigrationTarget02__factory.bytecode = _bytecode;
    MockVanillaV1MigrationTarget02__factory.abi = _abi;
    return MockVanillaV1MigrationTarget02__factory;
}(ethers_1.ContractFactory));
exports.MockVanillaV1MigrationTarget02__factory = MockVanillaV1MigrationTarget02__factory;
