"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.VanillaV1Constants02__factory = void 0;
var ethers_1 = require("ethers");
var _abi = [
    {
        inputs: [
            {
                internalType: "uint256",
                name: "allowed",
                type: "uint256",
            },
            {
                internalType: "uint256",
                name: "actual",
                type: "uint256",
            },
        ],
        name: "AllowanceExceeded",
        type: "error",
    },
    {
        inputs: [
            {
                internalType: "uint256",
                name: "expected",
                type: "uint256",
            },
            {
                internalType: "int256",
                name: "amountReceived",
                type: "int256",
            },
        ],
        name: "InvalidSwap",
        type: "error",
    },
    {
        inputs: [],
        name: "InvalidUniswapState",
        type: "error",
    },
    {
        inputs: [],
        name: "InvalidWethAccount",
        type: "error",
    },
    {
        inputs: [
            {
                internalType: "address",
                name: "owner",
                type: "address",
            },
            {
                internalType: "address",
                name: "token",
                type: "address",
            },
        ],
        name: "NoTokenPositionFound",
        type: "error",
    },
    {
        inputs: [
            {
                internalType: "uint256",
                name: "expected",
                type: "uint256",
            },
            {
                internalType: "uint256",
                name: "actual",
                type: "uint256",
            },
        ],
        name: "SlippageExceeded",
        type: "error",
    },
    {
        inputs: [
            {
                internalType: "uint256",
                name: "tokens",
                type: "uint256",
            },
            {
                internalType: "uint112",
                name: "balance",
                type: "uint112",
            },
        ],
        name: "TokenBalanceExceeded",
        type: "error",
    },
    {
        inputs: [],
        name: "TooManyTradesPerBlock",
        type: "error",
    },
    {
        inputs: [],
        name: "TradeExpired",
        type: "error",
    },
    {
        inputs: [
            {
                internalType: "address",
                name: "invalidVersion",
                type: "address",
            },
        ],
        name: "UnapprovedMigrationTarget",
        type: "error",
    },
    {
        inputs: [],
        name: "UnauthorizedCallback",
        type: "error",
    },
    {
        inputs: [],
        name: "UnauthorizedDelegateCall",
        type: "error",
    },
    {
        inputs: [],
        name: "UnauthorizedReentrantAccess",
        type: "error",
    },
    {
        inputs: [],
        name: "UnauthorizedValueSent",
        type: "error",
    },
    {
        inputs: [
            {
                internalType: "address",
                name: "token",
                type: "address",
            },
            {
                internalType: "uint24",
                name: "fee",
                type: "uint24",
            },
        ],
        name: "UninitializedUniswapPool",
        type: "error",
    },
    {
        inputs: [],
        name: "WrongTradingParameters",
        type: "error",
    },
];
var VanillaV1Constants02__factory = /** @class */ (function () {
    function VanillaV1Constants02__factory() {
    }
    VanillaV1Constants02__factory.createInterface = function () {
        return new ethers_1.utils.Interface(_abi);
    };
    VanillaV1Constants02__factory.connect = function (address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    };
    VanillaV1Constants02__factory.abi = _abi;
    return VanillaV1Constants02__factory;
}());
exports.VanillaV1Constants02__factory = VanillaV1Constants02__factory;
