name: Node.js CI

on:
  push:
    branches: [ main, next ]
  pull_request:
    branches: [ main, next ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: |
          npm install -g pnpm
          npm install
      - run: |
          cd src/contracts
          pnpm install
          pnpm run compile:sol
          pnpm run generate:typechain
          cd ../..
      - run: npm test
        env:
          RPC_URL: ${{ secrets.RPC_URL }}
