name: Node.js CI

on:
  push:
    branches: [ main, next ]
  pull_request:
    branches: [ main, next ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14
        cache: 'npm'
    - run: npm install
    - run: npm run build
    - run: npm test
      env:
        RPC_URL: ${{ secrets.RPC_URL }}
