name: Node.js CI

on:
  pull_request:
    branches: [ main, next ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Check node_modules cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install
      - run: yarn bootstrap
      - run: yarn build
      - run: yarn lint
      - run: yarn test
        env:
          RPC_URL: ${{ secrets.RPC_URL }}
          POLYGON_RPC_URL: ${{ secrets.POLYGON_RPC_URL }}
          JUICE_ADDRESS: ${{ secrets.JUICE_ADDRESS }}
